version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.7-ubuntu2204
    ports: 
      - 27017:27017
    networks:
      - peerprepnet
    container_name: mongodb
  
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    container_name: user-service
    ports:
      - 8001:8001
    depends_on:
      - mongodb
    networks:
      - peerprepnet

  question-service:
    build:
      context: ./question-service/backend
      dockerfile: Dockerfile
    env_file:
      - ./question-service/backend/.env
    container_name: question-service
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - peerprepnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # env_file:
    #   - ./frontend/.env
    container_name: frontend
    depends_on:
      - user-service
      - question-service
    networks:
      - peerprepnet
    
networks:
  peerprepnet:
    name: peerprepnet